"""The committed data files must agree with each other and with the code that
consumes them. Nothing here loads a model or needs a network."""

import json
from collections import Counter

import pandas as pd

from eval.species_mapping import OXFORD_TO_BLOOMLENS, UNCOVERED_SPECIES
from src import pricing
from tests.conftest import REPO_ROOT

FIELDS = {"common_name", "scientific_name", "taxonomy_string", "description"}


def names(species_list):
    return [s["common_name"] for s in species_list]


class TestSpeciesReference:
    def test_there_are_thirty_curated_species(self, species_list):
        assert len(species_list) == 30

    def test_every_entry_has_exactly_the_expected_non_empty_string_fields(self, species_list):
        for entry in species_list:
            assert set(entry) == FIELDS, entry.get("common_name")
            assert all(isinstance(v, str) and v.strip() for v in entry.values()), entry["common_name"]

    def test_names_are_unique(self, species_list):
        assert len(set(names(species_list))) == len(species_list)
        assert len({s["scientific_name"] for s in species_list}) == len(species_list)

    def test_taxonomy_strings_are_plantae_and_end_in_the_scientific_name(self, species_list):
        for s in species_list:
            assert s["taxonomy_string"].startswith("Plantae "), s["common_name"]
            assert s["taxonomy_string"].endswith(s["scientific_name"]), s["common_name"]


class TestPricingCoversEverySpecies:
    def test_every_species_has_a_base_price_and_none_are_orphaned(self, species_list):
        """Adding a species without a base price would silently price it at the 0.50
        fallback; a removed species leaving a price behind is stale data."""
        assert set(pricing._BASE_PRICE) == set(names(species_list))

    def test_base_prices_are_positive(self):
        assert all(price > 0 for price in pricing._BASE_PRICE.values())

    def test_the_committed_price_csv_covers_every_species_and_grade(self, species_list):
        df = pd.read_csv(REPO_ROOT / "data" / "simulated_prices.csv")
        assert list(df.columns) == ["species", "grade", "date", "price_per_stem"]
        assert set(df["species"]) == set(names(species_list))
        assert set(df["grade"]) == set(pricing.GRADES)
        # 30 species x 3 grades, each a full series (dates themselves are allowed to
        # be stale: the CSV is regenerated by scripts/build_index.py)
        assert len(df.groupby(["species", "grade"])) == 90
        assert (df["price_per_stem"] > 0).all()


class TestEvalMapping:
    def test_mapped_and_uncovered_species_partition_the_curated_thirty(self, species_list):
        mapped = set(OXFORD_TO_BLOOMLENS.values())
        uncovered = set(UNCOVERED_SPECIES)
        assert mapped | uncovered == set(names(species_list))
        assert mapped & uncovered == set()
        assert len(mapped) == 18 and len(uncovered) == 12

    def test_every_uncovered_species_states_a_reason(self):
        assert all(reason.strip() for reason in UNCOVERED_SPECIES.values())


class TestEvalTestSet:
    def load(self):
        return json.loads((REPO_ROOT / "eval" / "test_set.json").read_text(encoding="utf-8"))

    def test_it_is_360_images_across_the_18_mapped_species_evenly(self):
        entries = self.load()
        assert len(entries) == 360
        counts = Counter(e["species"] for e in entries)
        assert set(counts) == set(OXFORD_TO_BLOOMLENS.values())
        assert set(counts.values()) == {20}

    def test_every_image_exists_and_none_repeats(self):
        entries = self.load()
        paths = [e["image_path"] for e in entries]
        assert len(set(paths)) == len(paths)
        missing = [p for p in paths if not (REPO_ROOT / "eval" / p).is_file()]
        assert missing == []
